# Generated by Django 5.0.3 on 2024-03-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockProductos', '0003_gabinete'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesador',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
