# Generated by Django 5.0.3 on 2024-03-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockProductos', '0004_procesador_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabinete',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='placavideo',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teclado',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
